In [10]:
class Employee:
    total_employees = 0  # Class-level variable to count the number of Employees

    def __init__(self, name, family, salary, department):
        self.name = name
        self.family = family
        self.salary = salary
        self.department = department
        Employee.total_employees += 1  # Increment the count of employees

    @staticmethod
    def average_salary(employees):
        total_salary = sum(employee.salary for employee in employees)
        return total_salary / len(employees)

class FulltimeEmployee(Employee):
    pass


employee1 = Employee("harsha", "harsha Family", 75, "ind")
employee2 = Employee("sai", "sai  Family", 67, "business")


fulltime_employee1 = FulltimeEmployee("krishna", "krishna's Family", 88, "Farming")
fulltime_employee2 = FulltimeEmployee("sai", "sai's Family", 67, "Fancy")


employees = [employee1, employee2, fulltime_employee1, fulltime_employee2]
avg_salary = Employee.average_salary(employees)

print("Total Employees:", Employee.total_employees)
print("Average Salary:", avg_salary)

Total Employees: 4
Average Salary: 74.25


In [11]:
import numpy as np


random_vector = np.random.uniform(1, 20, 20)


reshaped_array = random_vector.reshape(4, 5)


reshaped_array[np.arange(4), np.argmax(reshaped_array, axis=1)] = 0

print("Original random vector:")
print(random_vector)
print("\nReshaped array:")
print(reshaped_array)


Original random vector:
[ 2.07373404  3.7286712   0.         11.68108035  3.75227681 16.36770254
  9.28255891  5.59581864  0.         10.78586622  9.56486278  5.74541579
 13.80553949  0.          9.31500296  6.479609    6.66217758 10.27352022
  0.         13.70011171]

Reshaped array:
[[ 2.07373404  3.7286712   0.         11.68108035  3.75227681]
 [16.36770254  9.28255891  5.59581864  0.         10.78586622]
 [ 9.56486278  5.74541579 13.80553949  0.          9.31500296]
 [ 6.479609    6.66217758 10.27352022  0.         13.70011171]]
